version: "3"

# docker run -it -p 8545:8545 -p 30303:30303 ethereum/client-go --rpc --rpcaddr "0.0.0.0"

services:
  blockchain:
    image: ethereum/client-go
    # build:
    #   context: "./docker"
    container_name: blockchain
    command: --rpc --rpcaddr "0.0.0.0" --syncmode "fast" --ws --wsorigins "*" --wsaddr "0.0.0.0"
    volumes:
      - ${PWD}:/go
      - ${PWD}/ethereum:/root/.ethereum
      - ${HOME}/.ssh:/root/.ssh
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"

  dev:
    image: schoeffm/vimux:powerline
    container_name: dev
    entrypoint: "/bin/zsh"
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ${GOPATH}:/go
    links:
      - "blockchain"
